{% set version = "1.4-8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-maptree
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/maptree_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/maptree/maptree_{{ version }}.tar.gz
  sha256: 55cf12af55540e7d53c8a7ae4bf87e192f5dec4161b3cdf2146689e8c8b465f4

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-cluster
    - r-rpart
  run:
    - r-base
    - r-cluster
    - r-rpart

test:
  commands:
    - $R -e "library('maptree')"           # [not win]
    - "\"%R%\" -e \"library('maptree')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=maptree
  license: Unlimited
  summary: Functions with example data for graphing, pruning, and mapping models from hierarchical clustering, and classification and regression trees.
  license_family: OTHER
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
