{% set version = "1.4-9" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-maptree
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/maptree_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/maptree/maptree_{{ version }}.tar.gz
  sha256: dddc188c6a137889624f4348a105891d4df4afe7785da536a21b725d4f93a6d6

build:
  noarch: generic
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-cluster
    - r-rpart
  run:
    - r-base
    - r-cluster
    - r-rpart

test:
  commands:
    - $R -e "library('maptree')"           # [not win]
    - "\"%R%\" -e \"library('maptree')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=maptree
  license: Unlimited
  summary: Functions with example data for graphing, pruning, and mapping models from hierarchical clustering, and classification and regression trees.
  license_family: OTHER
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
